/*
Deployment script for CICD_DEV

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "CICD_DEV"
:setvar DefaultFilePrefix "CICD_DEV"
:setvar DefaultDataPath "D:\SQL2025\MSSQL17.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "D:\SQL2025\MSSQL17.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE,
                DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating Table [dbo].[Customer]...';


GO
CREATE TABLE [dbo].[Customer] (
    [CustomerID]  INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]   NVARCHAR (100) NOT NULL,
    [LastName]    NVARCHAR (100) NOT NULL,
    [Email]       NVARCHAR (255) NULL,
    [Phone]       NVARCHAR (30)  NULL,
    [CreatedDate] DATETIME2 (0)  NOT NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([CustomerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[OrderDetail]...';


GO
CREATE TABLE [dbo].[OrderDetail] (
    [OrderDetailID] INT             IDENTITY (1, 1) NOT NULL,
    [OrderID]       INT             NOT NULL,
    [ProductID]     INT             NOT NULL,
    [Quantity]      INT             NOT NULL,
    [UnitPrice]     DECIMAL (18, 2) NOT NULL,
    CONSTRAINT [PK_OrderDetail] PRIMARY KEY CLUSTERED ([OrderDetailID] ASC)
);


GO
PRINT N'Creating Table [dbo].[OrderHeader]...';


GO
CREATE TABLE [dbo].[OrderHeader] (
    [OrderID]     INT           IDENTITY (1, 1) NOT NULL,
    [CustomerID]  INT           NOT NULL,
    [OrderDate]   DATETIME2 (0) NOT NULL,
    [OrderStatus] VARCHAR (30)  NOT NULL,
    CONSTRAINT [PK_OrderHeader] PRIMARY KEY CLUSTERED ([OrderID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Product]...';


GO
CREATE TABLE [dbo].[Product] (
    [ProductID]   INT             IDENTITY (1, 1) NOT NULL,
    [ProductName] NVARCHAR (200)  NOT NULL,
    [Price]       DECIMAL (18, 2) NOT NULL,
    [IsActive]    BIT             NOT NULL,
    CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([ProductID] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Customer_CreatedDate]...';


GO
ALTER TABLE [dbo].[Customer]
    ADD CONSTRAINT [DF_Customer_CreatedDate] DEFAULT (SYSUTCDATETIME()) FOR [CreatedDate];


GO
PRINT N'Creating Default Constraint [dbo].[DF_OrderHeader_OrderDate]...';


GO
ALTER TABLE [dbo].[OrderHeader]
    ADD CONSTRAINT [DF_OrderHeader_OrderDate] DEFAULT (SYSUTCDATETIME()) FOR [OrderDate];


GO
PRINT N'Creating Default Constraint [dbo].[DF_OrderHeader_OrderStatus]...';


GO
ALTER TABLE [dbo].[OrderHeader]
    ADD CONSTRAINT [DF_OrderHeader_OrderStatus] DEFAULT ('NEW') FOR [OrderStatus];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Product_IsActive]...';


GO
ALTER TABLE [dbo].[Product]
    ADD CONSTRAINT [DF_Product_IsActive] DEFAULT (1) FOR [IsActive];


GO
PRINT N'Creating Foreign Key [dbo].[FK_OrderDetail_Product]...';


GO
ALTER TABLE [dbo].[OrderDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_OrderDetail_Product] FOREIGN KEY ([ProductID]) REFERENCES [dbo].[Product] ([ProductID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_OrderDetail_OrderHeader]...';


GO
ALTER TABLE [dbo].[OrderDetail] WITH NOCHECK
    ADD CONSTRAINT [FK_OrderDetail_OrderHeader] FOREIGN KEY ([OrderID]) REFERENCES [dbo].[OrderHeader] ([OrderID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_OrderHeader_Customer]...';


GO
ALTER TABLE [dbo].[OrderHeader] WITH NOCHECK
    ADD CONSTRAINT [FK_OrderHeader_Customer] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customer] ([CustomerID]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_OrderDetail_UnitPrice]...';


GO
ALTER TABLE [dbo].[OrderDetail] WITH NOCHECK
    ADD CONSTRAINT [CK_OrderDetail_UnitPrice] CHECK ([UnitPrice] >= 0);


GO
PRINT N'Creating Check Constraint [dbo].[CK_OrderDetail_Quantity]...';


GO
ALTER TABLE [dbo].[OrderDetail] WITH NOCHECK
    ADD CONSTRAINT [CK_OrderDetail_Quantity] CHECK ([Quantity] > 0);


GO
PRINT N'Creating Check Constraint [dbo].[CK_Product_Price]...';


GO
ALTER TABLE [dbo].[Product] WITH NOCHECK
    ADD CONSTRAINT [CK_Product_Price] CHECK ([Price] >= 0);


GO
PRINT N'Creating View [dbo].[vw_CustomerOrders]...';


GO
CREATE VIEW [dbo].[vw_CustomerOrders]
AS
SELECT
    c.CustomerID,
    c.FirstName,
    c.LastName,
    o.OrderID,
    o.OrderDate,
    o.OrderStatus,
    SUM(od.Quantity * od.UnitPrice) AS OrderTotal
FROM dbo.Customer AS c
INNER JOIN dbo.OrderHeader AS o
    ON c.CustomerID = o.CustomerID
INNER JOIN dbo.OrderDetail AS od
    ON o.OrderID = od.OrderID
GROUP BY
    c.CustomerID,
    c.FirstName,
    c.LastName,
    o.OrderID,
    o.OrderDate,
    o.OrderStatus;
GO
PRINT N'Creating Function [dbo].[fn_GetCustomerOrderCount]...';


GO
CREATE FUNCTION [dbo].[fn_GetCustomerOrderCount]
(
    @CustomerID INT
)
RETURNS INT
AS
BEGIN
    DECLARE @OrderCount INT;

    SELECT
        @OrderCount = COUNT(*)
    FROM dbo.OrderHeader
    WHERE CustomerID = @CustomerID;

    RETURN ISNULL(@OrderCount, 0);
END;
GO
PRINT N'Creating Procedure [dbo].[usp_GetCustomer]...';


GO
CREATE PROCEDURE [dbo].[usp_GetCustomer]
    @CustomerID INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        CustomerID,
        FirstName,
        LastName,
        Email,
        Phone,
        CreatedDate
    FROM dbo.Customer
    WHERE CustomerID = @CustomerID;
END;
GO
PRINT N'Creating Procedure [dbo].[usp_GetOrders]...';


GO
CREATE PROCEDURE [dbo].[usp_GetOrders]
    @CustomerID INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        o.OrderID,
        o.OrderDate,
        o.OrderStatus,
        SUM(od.Quantity * od.UnitPrice) AS OrderTotal
    FROM dbo.OrderHeader AS o
    INNER JOIN dbo.OrderDetail AS od
        ON o.OrderID = od.OrderID
    WHERE o.CustomerID = @CustomerID
    GROUP BY
        o.OrderID,
        o.OrderDate,
        o.OrderStatus
    ORDER BY
        o.OrderDate DESC;
END;
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[OrderDetail] WITH CHECK CHECK CONSTRAINT [FK_OrderDetail_Product];

ALTER TABLE [dbo].[OrderDetail] WITH CHECK CHECK CONSTRAINT [FK_OrderDetail_OrderHeader];

ALTER TABLE [dbo].[OrderHeader] WITH CHECK CHECK CONSTRAINT [FK_OrderHeader_Customer];

ALTER TABLE [dbo].[OrderDetail] WITH CHECK CHECK CONSTRAINT [CK_OrderDetail_UnitPrice];

ALTER TABLE [dbo].[OrderDetail] WITH CHECK CHECK CONSTRAINT [CK_OrderDetail_Quantity];

ALTER TABLE [dbo].[Product] WITH CHECK CHECK CONSTRAINT [CK_Product_Price];


GO
PRINT N'Update complete.';


GO
