name: SQL Server CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: windows-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build SQL Database Project
        shell: pwsh
        run: |
          dotnet build CICDDemoDB/CICDDemoDB.sqlproj --configuration Release

      - name: Verify DACPAC
        shell: pwsh
        run: |
          $dacpac = "CICDDemoDB/bin/Release/CICDDemoDB.dacpac"

          if (!(Test-Path $dacpac)) {
              throw "DACPAC was not created."
          }

          Write-Host "DACPAC created successfully:"
          Write-Host $dacpac